version: 2

common_steps: &common_steps
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run tests
          command: npm run mocha

      - run:
          name: Check Typescript types
          command: npm run check-types
          when: always

jobs:
  node-14:
    docker:
      - image: cimg/node:14.21.1


    <<: *common_steps

  node-16:
    docker:
      - image: cimg/node:16.19.0

    <<: *common_steps

  node-18:
    docker:
      - image: cimg/node:18.12.1

    <<: *common_steps

  node-19:
    docker:
      - image: cimg/node:19.3.0

    <<: *common_steps

workflows:
  version: 2

  on-commit:
    jobs:
      - node-14
      - node-16
      - node-18
      - node-19
